import Link from 'next/link'
import React from 'react'
import Head from 'next/head'




function Home() {
  return (
    <>
    <Head>
        <title>Indushree M Patil</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div className=''>
{/*  navbar start*/}
<header>
    <div className='fixed flex w-full gap-4 justify-center bg-[#facfe7] items-center text-black'>
    <div className='h-12 w-full items-center flex' >
    <div className=' pl-20 max-w-3xl mx-auto  flex justify-center gap-5 text-2xl '>
            <button className='flex gap-5'>
            <Link href="/Home/#section1"><h1 className='cursor-pointer '>Home</h1></Link>
            <Link href="/Home/#section2"><h1 className='cursor-pointer  pr-3'>About Me</h1></Link>
            <Link href="/Home/#section3"><h1 className='cursor-pointer  pr-3'>Project</h1></Link>
            <Link href="/Home/#section4"><h1 className='cursor-pointer  pr-3'>Contact</h1></Link>
            </button>
                        

              
            </div>
            <div className='pr-8'>
              <a href='https://github.com/indu-987' target="blanck" rel="noreferrer" >
                <img src='/assets/image/github.svg' className='h-10 w-10 '></img>
                </a>    
        
            </div>
            <div className='pr-8'>
              <a href='https://www.linkedin.com/in/indushree-m-patil-8b1915242/' target="blanck" rel="noreferrer" >
                <img src='/assets/icon/linkedin.svg' className='h-10 w-10 '></img>
                </a>    
        
            </div>
    </div>
    </div>
    </header>
   {/*  nav bar end */}


   {/* section 1 Start */}
   <div>
     <div id='section1'>
      <div className="bg">
        <div className=' h-screen  text-black '>
          <div className='flex items-center '>
          <div  className="  pt-40 h-[500px] w-[500px]">
          <img src='https://computerscienced.co.uk/site/wp-content/uploads/2022/01/undraw_programmer_re_owql.svg ' className='h-full w-full'/>
          </div>
          <div className=' pt-40  h-[400px] w-[500px]   text-center   ' >
    
            <h1 className='font-Satisfy text-7xl text-Great'> Hello There!!!</h1>
            <h2 className='  pt-3  font-bold text-3xl'> I&apos;m  Indushree  M Patil</h2>
            <h3 className='text-2xl pt-3' >Software Developer</h3>
           
            <div  className=' pt-14'>
            <Link href="/Home/#section4">
              <button className='border-2 border-black h-10 w-20 font-bold'>
              Hire me
             </button></Link>
             
            </div>
            </div>
            
            
        </div>
          </div>
         
      </div>
    </div>
    {/* section 1 end */}
   
   {/* Section 2 Start */}
    <div id='section2'>
      <div className="sg h-screen flex justify-between">
        <div className=' pl-10 pt-16 w-[800px] h-[600px] '>
         
    <h2 className=' pb-10  flex gap-4   font-Dance text-5xl ' > 
        About Me
       </h2>
       
       <h3 className=' pb-10 pt-16 border-y-2 border-black font-Poppins '>I&apos;m Software developer,<br/>
        having experience in developing and building a real-time application for<br/>
         E-commerce , Entertainment platforms.<br/>

<br/>Few of my project includes:<br/>
 1. Twitter Cloning.<br/>
 2. Spotify Cloning.<br/>
 3. Disney Plus Cloning.<br/>

 <br/>I get excited about opportunity where I get challenges <br/>
 to solve problem in digital platform.
 I love connecting with new people ,<br/>
 You can reach me @ impatil987@gmail.com
      </h3>
       </div>
      <div  className="  flex  pt-40 h-[450px] w-[450px]">
        <img src='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRncFQEdqfa4vVRilPFBHG3zNXN3GF_uSUAlg&usqp=CAU'/>
      </div>
      
     
    </div>
    </div>
    {/* section 2 end */}

  {/* section 3 start */}
    <div id='section3'>
      <div className='s1g'>
        <div className='h-screen pt-10 pl-10'>
    <h2 className='pt-7  pl-10 flex gap-4   font-Dance text-5xl '>
        Projects
         </h2>
        <div className='pt-8'>
        <div className='h-[200px] w-[500px]  border-y-2 border-black justify-center gap-10 items-center flex shadow-lg'>
          <a href='https://disneyhotstar-zeta.vercel.app/' target="blanck" rel="noreferrer">

          <img src='https://www.exults.com/wp-content/uploads/howdisneybecameadisruptorinthestreamingmarket.jpg' className='h-[170px] w-[200px] rounded-lg transition ease-in-out hover:-translate-y-1 hover:scale-110 hover:duration-300'></img>
          </a>
          
          <h1 className='text-2xl '>Disney+</h1>        
        </div>
        </div>
        <div className='pt-10 justify-end items-end flex pr-20 pb-10'>
        <a href="https://twitter-six-delta.vercel.app/" target="blanck" rel="noreferrer">
        <div className='h-[200px] w-[500px]  border-y-2 border-black justify-center gap-10 items-center flex shadow-lg '>
        
         <h1 className='text-2xl '>Twitter</h1>  
          <img src='https://images.unsplash.com/photo-1611605698335-8b1569810432?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8dHdpdHRlcnxlbnwwfHwwfHw%3D&w=1000&q=80' className='h-[170px] w-[200px] rounded-lg translate ease-in-out hover:-translate-y-1 hover:scale-110 hover:duration-500'></img>
                
        </div>
        </a>
        </div>




      </div>
    </div>
    </div>
    {/* section 3 end */}

     {/* Section 4 Start */}
     <div id='section4'>
      
     <div className=' s2g pl-5 h-screen pt-28 flex'>
                <div className='h-[600px] w-[650px] space-y-5'>
                <h1 className='text-5xl font-dance font-bold text-center pt-7'>Contact</h1>
                <div className='h-[300px] w-[600px] border-y-2 space-y-5 border-gray-400  '>
                    <div className='flex  items-center gap-5 pt-16'>
                        <img src='/assets/icon/gmail.svg' className='h-[80px] w-[80px]'></img>
                        <h2 className='text-3xl font-Damion'>impatil987@gmail.com</h2>
                      
                       </div>
                   

                    <div className='flex  items-center gap-5 '>
                        <img src='/assets/icon/linkedin.svg' className='h-[80px] w-[80px]'></img>
                        <a href='https://www.linkedin.com/in/indushree-m-patil-8b1915242/' target="blanck" rel="noreferrer">
                        <h2 className='text-2xl font-Damion'> linkedin.com/in/indushree-m-patil</h2>
                        </a>
                    </div>

                </div>

                </div>


            <img src='/assets/image/buffer.svg' className='h-[400px] w-[500px]'></img>
        
        </div>
       
     
      
    
    </div>
    </div>
    {/* Sextion 4 end */}


   
    {/* fotter start */}
    <div>
        <div className='h-52 max-w-78l mx-auto bg-black'>
            
    <h2>
        Fotter
      </h2>
      </div>
    </div>
    {/* fotter end */}
    </div>
    </>
  )
}

export default Home
