import Head from 'next/head'
import Image from 'next/image'
import Home from './Home'

export default function Index() {
  return (
    <div >
      <Head>
        <title>Indushree M Patil</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
           
<Home/>
      
    </div>
  )
}
